### ISSUE TITLE
The "Incomplete" titan is spelled differently in different places

### ISSUE THREAD

**Issue by death506** [8thaxisgaming/8thAxis-Public#12]
The "Incomplete" titan is currently spelled differently in 2 commands.

Aot 1.20.2

In the command  /aot giveform IncompleteForm  it is spelled as "IncompleteForm"
But in the command  /shift Incomplete  it is only spelled as "Incomplete"

**Comment by LilWoetroe** [comment]
How do you want it to be spelled? I'll change that to however you want it

**Comment by LilWoetroe** [comment]
Should be fixed!
Gave the form to myself as `Incomplete` autotab suggest `Incomplete` and when shifting its also `Incomplete`
Closing the ticket.
