### ISSUE TITLE
Checking other player's tks doesnt work

### ISSUE THREAD

**Issue by death506** [8thaxisgaming/8thAxis-Public#15]
Doing /tks [PlayerName] to check someone's tks other than your own doesn't work.

AOT 1.20.2

ggrxxn reported that  /tks [PlayerName]  doesn't work. OPed players can view other player's tks.
Upon a normal player trying to do this command this message appears "Incorrect argument for command"

**Comment by LilWoetroe** [comment]
Fixed might need to look into removing teh @e @p @ stuff in general.
Normal players now have acces to the TKS command and its no longer locked behind the aot.enabled or aot.moderation perm.
