### ISSUE TITLE
Armor Damage = 1 stops durability

### ISSUE THREAD

**Issue by death506** [8thaxisgaming/8thAxis-Public#5]
Armor Damage = 1 stops durability

AOT 1.20.2

If armor damage is set to 1 on a kenn, the durability stops working. I tested this with the starter's kenn.
Kenns with any other armor damage stat work fine, but if a kenn's armor damage is set to 1 (for any kenn) the durability fully stops working.

**Comment by LilWoetroe** [comment]
I'll check the code when I look into the bug that's messing up the display name in killstreak messages. It's either a math error or it requires multiple conditions to count durability damage. Damage for eyes and knees and even hand are all seperate systems within the hit damage action.

**Comment by LilWoetroe** [comment]
Math was indeed bad. With specifying 1 as damage the durability damage (amount to take of the item) would have been under 0.5 which rounds it to 0. Redid the line to a 1:1 system where damage = durability. 1 Armor damage *Should* take 1 durability hit. 50 Armor should take 50 durability.
